server:
  port: 8080
spring:
  application:
    name: "gateway-server"
#  cloud:
#    gateway:
#      routes:
#        - id: shorten-api
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/shorten/**
#        - id: redirect-api
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/r/**