server:
  port: 8080
spring:
  application:
    name: "gateway-server"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
#  cloud:
#    gateway:
#      routes:
#        - id: shorten-api
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/shorten/**
#        - id: redirect-api
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/r/**