server:
  port: 8082
spring:
  application:
    name: "redirect-api"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

sharding:
  count: 2
  shards:
      0:
        url: ${SHARD_0_URL}
        username: ${SHARD_0_USERNAME}
        password: ${SHARD_0_PASSWORD}
      password: root
      1:
        url: ${SHARD_1_URL}
        username: ${SHARD_1_USERNAME}
        password: ${SHARD_1_PASSWORD}


