server:
  port: 8081
spring:
  application:
    name: "shorten-api"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never

  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

shard:
  count: 2
  0:
    jdbc-url: ${SHARD_0_URL}
    username: ${SHARD_0_USERNAME}
    password: ${SHARD_0_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: ${SHARD_0_URL_REPLICA}
      username: ${SHARD_0_USERNAME_REPLICA}
      password: ${SHARD_0_PASSWORD_REPLICA}
      driver-class-name: com.mysql.cj.jdbc.Driver
  1:
    jdbc-url: ${SHARD_1_URL}
    username: ${SHARD_1_USERNAME}
    password: ${SHARD_1_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: ${SHARD_1_URL_REPLICA}
      username: ${SHARD_1_USERNAME_REPLICA}
      password: ${SHARD_1_PASSWORD_REPLICA}
      driver-class-name: com.mysql.cj.jdbc.Driver