server:
  port: 8081
spring:
  application:
    name: "shorten-api"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

sharding:
  count: 2
  shards:
    0:
      url: ${SHARD_0_URL}
      username: ${SHARD_0_USERNAME}
      password: ${SHARD_0_PASSWORD}
    1:
      url: ${SHARD_1_URL}
      username: ${SHARD_1_USERNAME}
      password: ${SHARD_1_PASSWORD}

  replicaShards:
    0:
      url: ${SHARD_0_URL_REPLICA}
      username: ${SHARD_0_USERNAME_REPLICA}
      password: ${SHARD_0_PASSWORD_REPLICA}
    1:
      url: ${SHARD_1_URL_REPLICA}
      username: ${SHARD_1_USERNAME_REPLICA}
      password: ${SHARD_1_PASSWORD_REPLICA}

  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always