
services:
  url-db-shard-0-master:
    image: mysql
    container_name: url-db-0-master
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: url-db-0-master
    volumes:
      - ../mysql/scripts/shard-0-master-init.sh:/docker-entrypoint-initdb.d/master-init.sh
      - ../mysql/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../mysql/config/master-0.cnf:/etc/mysql/conf.d/master.cnf
    extends:
      file: common-config.yml
      service: microservice-db-config

  url-db-shard-0-replica:
    image: mysql
    container_name: url-db-0-replica
    ports:
      - "3308:3306"
    depends_on:
      url-db-shard-0-master:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: url-db-0-replica
    volumes:
      - ../mysql/scripts/shard-0-replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh
      - ../mysql/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../mysql/config/replica-0.cnf:/etc/mysql/conf.d/replica.cnf
    extends:
      file: common-config.yml
      service: microservice-db-config

  url-db-shard-1-master:
    image: mysql
    container_name: url-db-1-master
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: url-db-1-master
    volumes:
      - ../mysql/scripts/shard-1-master-init.sh:/docker-entrypoint-initdb.d/master-init.sh
      - ../mysql/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../mysql/config/master-1.cnf:/etc/mysql/conf.d/master.cnf
    extends:
      file: common-config.yml
      service: microservice-db-config

  url-db-shard-1-replica:
    image: mysql
    container_name: url-db-1-replica
    ports:
      - "3310:3306"
    depends_on:
      url-db-shard-1-master:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: url-db-1-replica
    volumes:
      - ../mysql/scripts/shard-1-replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh
      - ../mysql/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../mysql/config/replica-1.cnf:/etc/mysql/conf.d/replica.cnf
    extends:
      file: common-config.yml
      service: microservice-db-config

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  shorten-api:
     image: "zell1502/shorten-api:s1"
     container_name: shorten-api
     healthcheck:
       test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
       interval: 5s
       timeout: 5s
       retries: 20
       start_period: 10s
     ports:
       - "8081:8081"
     depends_on:
       url-db-shard-0-master:
         condition: service_healthy
       url-db-shard-0-replica:
         condition: service_healthy
       url-db-shard-1-master:
         condition: service_healthy
       url-db-shard-1-replica:
         condition: service_healthy
       redis:
         condition: service_healthy
       eureka-server:
         condition: service_healthy
     environment:
        SPRING_APPLICATION_NAME: "shorten-api"
        SPRING_DATA_REDIS_HOST: redis
        SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
        SPRING_DATA_REDIS_PORT: 6379
        SPRING_DATA_REDIS_TIMEOUT: 1s
        SHARD_0_URL: jdbc:mysql://url-db-shard-0-master:3306/url-db-0-master
        SHARD_0_USERNAME: root
        SHARD_0_PASSWORD: root
        SHARD_0_URL_REPLICA: jdbc:mysql://url-db-shard-0-replica:3306/url-db-0-replica
        SHARD_0_USERNAME_REPLICA: root
        SHARD_0_PASSWORD_REPLICA: root
        SHARD_1_URL: jdbc:mysql://url-db-shard-1-master:3306/url-db-1-master
        SHARD_1_USERNAME: root
        SHARD_1_PASSWORD: root
        SHARD_1_URL_REPLICA: jdbc:mysql://url-db-shard-1-replica:3306/url-db-1-replica
        SHARD_1_USERNAME_REPLICA: root
        SHARD_1_PASSWORD_REPLICA: root
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
     extends:
        file: common-config.yml
        service: network-deploy-service

  redirect-api:
     image: "zell1502/redirect-api:s1"
     container_name: redirect-api
     healthcheck:
       test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
       interval: 5s
       timeout: 5s
       retries: 20
       start_period: 5s
     ports:
       - "8082:8082"
     depends_on:
       shorten-api:
         condition: service_healthy
       url-db-shard-0-master:
         condition: service_healthy
       url-db-shard-0-replica:
         condition: service_healthy
       url-db-shard-1-master:
         condition: service_healthy
       url-db-shard-1-replica:
         condition: service_healthy
       redis:
         condition: service_healthy
       eureka-server:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "redirect-api"
       SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
       SPRING_DATA_REDIS_HOST: redis
       SPRING_DATA_REDIS_PORT: 6379
       SPRING_DATA_REDIS_TIMEOUT: 1s
       SHARD_0_URL: jdbc:mysql://url-db-shard-0-master:3306/url-db-0-master
       SHARD_0_USERNAME: root
       SHARD_0_PASSWORD: root
       SHARD_0_URL_REPLICA: jdbc:mysql://url-db-shard-0-replica:3306/url-db-0-replica
       SHARD_0_USERNAME_REPLICA: root
       SHARD_0_PASSWORD_REPLICA: root
       SHARD_1_URL: jdbc:mysql://url-db-shard-1-master:3306/url-db-1-master
       SHARD_1_USERNAME: root
       SHARD_1_PASSWORD: root
       SHARD_1_URL_REPLICA: jdbc:mysql://url-db-shard-1-replica:3306/url-db-1-replica
       SHARD_1_USERNAME_REPLICA: root
       SHARD_1_PASSWORD_REPLICA: root
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
     extends:
       file: common-config.yml
       service: network-deploy-service

  
  gateway-api:
     image: "zell1502/gateway-api:s1"
     container_name: gateway-api
     healthcheck:
       test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
       interval: 5s
       timeout: 5s
       retries: 20
       start_period: 5s
     ports:
       - "8080:8080"
     depends_on:
       redirect-api:
         condition: service_healthy
       shorten-api:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "gateway-api"
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
     extends:
       file: common-config.yml
       service: network-deploy-service

  eureka-server:
    image: "zell1502/eureka-server:s1"
    container_name: eureka-server
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service


networks:
  urlshortener:
    driver: "bridge"